# Generated by Django 3.2.9 on 2022-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=50)),
                ('sana', models.DateField()),
                ('mavzu', models.CharField(max_length=30)),
                ('muallif', models.CharField(max_length=30)),
            ],
        ),
    ]
